version: '3.9'

services:
  backend:
    build:
      context: ./EasyInvoice
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  frontend:
    build:
      context: ./client
    ports:
      - "80:80"
